### ISSUE TITLE
Language change for App

### ISSUE THREAD

**Issue by katiaru** [katiaru/apps-android-wikipedia#3]
As a client, I would like to have a possibility of changing the language of the menu of the app and the articles, so I can understand the information and navigate through the menu.

SP: 3
Priority: Medium
Risk: Medium
Ideal time: 10 hours
Demo steps:
Choose language in the menu. Page should reload in the selected language including all the app menu items and the article(s).

- [x] Implement the language change
- [x] Write and implement test cases

**Comment by Ricklig** [comment]
![27497240_10213593302161449_723599876_n](https://user-images.githubusercontent.com/6952519/35636885-8c5b81bc-0680-11e8-99e5-54f0bb6caacc.png)
![27496516_10213593302121448_1589703430_n](https://user-images.githubusercontent.com/6952519/35636887-8ca792e6-0680-11e8-8228-9494577bed98.png)

**Comment by katiaru** [comment]
This issue was moved to katiaru/wikipedia#4
