### ISSUE TITLE
Changing language from new button main menu

### ISSUE THREAD

**Issue by Ricklig** [katiaru/apps-android-wikipedia#5]
As a client, I would like to have a possibility of changing the language of the menu of the app and the articles, so I can understand the information and navigate through the menu, From the home screen. 
SP: 3
Priority: Medium
Risk: Medium
Ideal time: 10 hours
Demo steps:
Choose language from the main menu toolbar located on the bottom of the main menu interface. Page should reload in the selected language including all the app menu items and the article(s).

TODO: From the main menu
- [x] add button (same as in article) 
- [x] be able to change the language (system and article)
- [x] Test feature

**Comment by Ricklig** [comment]
Mock-ups

![27650192_10213593314241751_1208381487_o](https://user-images.githubusercontent.com/6952519/35636965-b67449a2-0680-11e8-84b1-3da29e123cb6.png)

**Comment by Ricklig** [comment]
![inked27650192_10213593314241751_1208381487_o_li](https://user-images.githubusercontent.com/6952519/35640299-c677feac-068a-11e8-892a-8fdb24201b87.jpg)

**Comment by Ricklig** [comment]
![27658253_10213604172233194_1492616986_n](https://user-images.githubusercontent.com/6952519/35715228-27a5ec6a-079f-11e8-93b1-ca074a22450c.png)


Better mockup

**Comment by katiaru** [comment]
This issue was moved to katiaru/wikipedia#2
